name: Test kubsh

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc make \
          libreadline-dev \
          libfuse3-dev \
          dpkg-dev
    
    - name: Build kubsh
      run: |
        make build
        make deb
    
    - name: Run tests
      run: |
        docker run \
          -v $(pwd)/kubsh:/usr/bin/kubsh \
          -v $(pwd)/kubsh_1.0_amd64.deb:/tmp/kubsh.deb \
          tyvik/kubsh_test:master \
          sh -c "dpkg -i /tmp/kubsh.deb || apt-get install -f -y && cd /opt && python3 -m pytest"
