name: Test kubsh

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Запуск тестов в Docker
      run: |
        docker run \
          --rm \
          --privileged \
          -v $(pwd):/build \
          tyvik/kubsh_test:master \
          sh -c "
            apt-get update
            apt-get install -y gcc make libreadline-dev libfuse3-dev
            cd /build
            gcc kubsh.c vfs.c -lreadline -lfuse3 -o kubsh
            cp kubsh /usr/bin/
            cd /opt && python3 -m pytest -v
          "
